#!/usr/bin/env python3
"""SFEN → TikZ 詰将棋図面 (詰パラ/将棋世界風).

詰将棋界隈の標準的な TikZ 図面環境 (マス 4.8mm×5.2mm, 外枠 0.4mm;
cf. https://silvertumekster.fc2.net/blog-entry-61.html) に倣う。
後手駒は 180 度回転。持駒は盤の左右に縦書き (☖=左, ☗=右)。

usage: python3 sfen2tikz.py '<sfen>' [cell_w_mm cell_h_mm] > out.tex
"""
import sys

PIECE = {
    'P': '歩', 'L': '香', 'N': '桂', 'S': '銀', 'G': '金', 'B': '角', 'R': '飛',
    'K': '王',
    '+P': 'と', '+L': '杏', '+N': '圭', '+S': '全', '+B': '馬', '+R': '龍',
}
HAND_ORDER = ['R', 'B', 'G', 'S', 'N', 'L', 'P']
NUM_KANJI = {2: '二', 3: '三', 4: '四', 5: '五', 6: '六', 7: '七', 8: '八',
             9: '九', 10: '十', 11: '十一', 12: '十二', 13: '十三', 14: '十四',
             15: '十五', 16: '十六', 17: '十七', 18: '十八'}


def parse_board(board):
    """returns list of (file, rank, kanji, is_gote)"""
    out = []
    for r, row in enumerate(board.split('/'), start=1):
        f = 9
        promoted = False
        for c in row:
            if c.isdigit():
                f -= int(c)
            elif c == '+':
                promoted = True
            else:
                is_gote = c.islower()
                key = ('+' if promoted else '') + c.upper()
                kanji = PIECE[key]
                if c == 'k':  # 受方玉
                    kanji = '玉'
                out.append((f, r, kanji, is_gote))
                promoted = False
                f -= 1
    return out


def parse_hand(hand):
    """returns {(is_gote, letter): count}"""
    res = {}
    if hand == '-':
        return res
    n = 0
    for c in hand:
        if c.isdigit():
            n = n * 10 + int(c)
        else:
            res[(c.islower(), c.upper())] = max(n, 1)
            n = 0
    return res


def hand_text(hand, gote):
    chars = []
    for p in HAND_ORDER:
        cnt = hand.get((gote, p))
        if cnt:
            chars.append(PIECE[p])
            if cnt > 1:
                chars += list(NUM_KANJI[cnt])
    if not chars:
        chars = ['な', 'し']
    return chars


def main():
    sfen = sys.argv[1]
    board, turn, hand = sfen.split()[:3]
    pieces = parse_board(board)
    hands = parse_hand(hand)

    w = sys.argv[2] if len(sys.argv) > 2 else '4.8'
    h = sys.argv[3] if len(sys.argv) > 3 else '5.2'
    print('% generated by sfen2tikz.py -- do not edit')
    print(f'% sfen: {sfen}')
    print(rf'\begin{{tikzpicture}}[x=-{w}mm,y=-{h}mm]')
    print(r'\foreach \i in {1,...,8} {')
    print(r'  \draw[line width=0.1mm] (\i,0) -- (\i,9);')
    print(r'  \draw[line width=0.1mm] (0,\i) -- (9,\i);}')
    print(r'\draw[line width=0.4mm] (0,0) rectangle (9,9);')
    print(r'\foreach \p in {(3,3),(6,3),(3,6),(6,6)}'
          r' \fill \p circle [radius=0.3mm];')
    for f, r, kanji, gote in pieces:
        opt = ',rotate=180' if gote else ''
        print(rf'\node[inner sep=0pt{opt}] at ({f - 0.5},{r - 0.5})'
              rf' {{\koma {kanji}}};')
    # 持駒: 後手=盤の左(玉側から見て右), 先手=盤の右
    for gote, x, mark in [(True, 9.75, r'☖'), (False, -0.75, r'☗')]:
        chars = [mark] + hand_text(hands, gote)
        for i, ch in enumerate(chars):
            print(rf'\node[inner sep=0pt] at ({x},{0.4 + 0.82 * i})'
                  rf' {{\mochi {ch}}};')
    print(r'\end{tikzpicture}')


if __name__ == '__main__':
    main()
