[package]
name = "fmrs_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }
serde_repr = "0.1.8"

[dev-dependencies]
pretty_assertions = "1.2.1"
serde_json = "1.0.82"
