#![allow(clippy::all, unused)]
use crate::position::bitboard::BitBoard;
#[doc = "Generated by gen-magic: total_len=515840 elapsed=247.2s"]
use crate::position::bitboard::Square;
const fn b(x: u128) -> BitBoard {
    BitBoard::from_u128(x)
}
pub struct Offset(usize);
#[cfg(not(feature = "gen-magic"))]
impl std::ops::Index<usize> for Offset {
    type Output = BitBoard;
    fn index(&self, index: usize) -> &Self::Output {
        &ALL[index + self.0]
    }
}
use crate::position::bitboard::rule::magics_generator::Magic;
use crate::position::bitboard::rule::magics_generator::Magics;
#[cfg(feature = "gen-magic")]
pub fn bishop_reachable(occupied: BitBoard, pos: Square) -> BitBoard {
    unimplemented!()
}
#[cfg(feature = "gen-magic")]
pub fn pro_bishop_reachable(occupied: BitBoard, pos: Square) -> BitBoard {
    unimplemented!()
}
#[cfg(feature = "gen-magic")]
pub fn rook_reachable(occupied: BitBoard, pos: Square) -> BitBoard {
    unimplemented!()
}
#[cfg(feature = "gen-magic")]
pub fn pro_rook_reachable(occupied: BitBoard, pos: Square) -> BitBoard {
    unimplemented!()
}
#[cfg(not(feature = "gen-magic"))]
include!("generated_magics_incl.rs");
