[package]
name = "fmrs"
version = "0.1.0"
authors = ["Keigo Oka <ogiekako@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[[bin]]
name = "fmrs"
bench = false

[workspace]
members = ["wasm", "fmrs_core"]

[dependencies]
fmrs_core = { path = "./fmrs_core" }
lazy_static = "1.4.0"

serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8"
bincode = "1.2.0"

rand = { version = "0.8.5", features = ["small_rng"] }
sled = { version = "0.34.7" } # default-features = false
percent-encoding = "2.1.0"
anyhow = "1.0.58"
clap = { version = "4", features = ["derive"] }
actix-web = "4.1.0"
serde_json = "1.0.81"
serde_repr = "0.1.8"
futures = "0.3.21"
actix-files = "0.6.1"
pprof = { version = "0.10.0", features = [
    "criterion",
    "flamegraph",
    "_protobuf",
    "protobuf-codec",
] }
sysinfo = "0.24.6"
tempfile = "3.3.0"
log = "0.4.22"
env_logger = "0.11.5"
rustc-hash = "2.1.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = { version = "0.3.6", features = ["html_reports"] }

[profile.dev]
opt-level = 1

[[bench]]
name = "bench"
harness = false
