[package]
name = "shtsume_rs"
version = "0.1.0"
edition = "2021"

[lib]

[[bin]]
name = "shtsume_rs"

[build-dependencies]
cc = { version = "*", features = ["parallel"] }
bindgen = "0.70"

[dependencies]
anyhow = "*"
libc = "*"
