#![allow(clippy::all, unused)]
use crate::position::bitboard::BitBoard;
#[doc = "Generated by gen-magic: total_len=515840 elapsed=28.1s"]
use crate::position::Square;
struct Offset(usize);
#[cfg(not(feature = "gen-magic"))]
impl std::ops::Index<usize> for Offset {
    type Output = BitBoard;
    fn index(&self, index: usize) -> &Self::Output {
        &ALL[self.0 + index]
    }
}
use crate::magic::Magic;
use crate::position::advance::pinned::magics_generator::Magics;
use crate::position::advance::pinned::magics_generator::PackMagic;
#[cfg(feature = "gen-magic")]
pub fn bishop_pinning(occupied: BitBoard, pos: Square) -> BitBoard {
    unimplemented!()
}
#[cfg(feature = "gen-magic")]
pub fn rook_pinning(occupied: BitBoard, pos: Square) -> BitBoard {
    unimplemented!()
}
#[cfg(not(feature = "gen-magic"))]
include!("generated_magics_incl.rs");
