#![allow(clippy::all, unused)]
use crate::position::bitboard::BitBoard;
#[doc = "Generated by gen-magic: total_len=515840 elapsed=33.5s"]
use crate::position::Square;
struct Offset {
    ids_offset: usize,
    all_offset: usize,
}
#[cfg(not(feature = "gen-magic"))]
impl std::ops::Index<usize> for Offset {
    type Output = BitBoard;
    fn index(&self, index: usize) -> &Self::Output {
        &ALL[self.all_offset + IDS[self.ids_offset + index] as usize]
    }
}
use crate::magic::Magic;
use crate::piece::Color;
use crate::position::advance::pinned::magics_generator::Magics;
use crate::position::advance::pinned::magics_generator::PackMagic;
#[cfg(feature = "gen-magic")]
pub fn lance_pinning(occupied: BitBoard, king_color: Color, pos: Square) -> BitBoard {
    unimplemented!()
}
#[cfg(feature = "gen-magic")]
pub fn bishop_pinning(occupied: BitBoard, pos: Square) -> BitBoard {
    unimplemented!()
}
#[cfg(feature = "gen-magic")]
pub fn rook_pinning(occupied: BitBoard, pos: Square) -> BitBoard {
    unimplemented!()
}
#[cfg(not(feature = "gen-magic"))]
include!("generated_magics_incl.rs");
