name: Rust Clippy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "./rust"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
