name: Rust Clippy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "./rust"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
      - run: cargo clippy
