name: Build and deploy github pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
      - name: Set up Rust
        # TODO: update to https://github.com/dtolnay/rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          # https://github.com/webpack/webpack/issues/15566#issuecomment-2421667784
          toolchain: 1.81.0
          default: true
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install & Build
        run: |
          npm ci
          npm run build
          rm ./docs/pkg/.gitignore
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: docs
          clean-exclude: dev
